### ISSUE TITLE
latency of ping probe result is not accurate when targets number is big

### ISSUE THREAD

**Issue by chenlujjj** [google/cloudprober#531] opened 2020-12-18 13:37 UTC
**Describe the bug**

The latency of ping probe result is not accurate when targets number is big

**Cloudprober Version**
v0.11.1

**To Reproduce**
1. compile the ping.go in probes/ping/cmd folder to binary file
2. use the ping to probe about 50 targets
3. the result shows that latency (corresponding to ping rtt) is bigger than the latency when pinging to each target respectively

**Additional context**

**Comment by manugarg** [comment] 2020-12-18 17:39
@chenlujjj Latency measurement depends on when outgoing packet is sent by the operating system and when incoming packet is received and processed by cloudprober. Increasing the number of targets can possibly cause delays if packets are not being delivered or processed fast enough -- it will likely  depend on many factors - CPU available, probe frequency, and possibly some operating system parameters as well. 

What kind of latency impact are you seeing? In our setup, we run ping probes with more than 1000 targets, using less than half a core. We don't see a difference in latency measurement that we care about (this setup is not to measure latency performance anyway -- as long as it's within a threshold).

**Comment by chenlujjj** [comment] 2020-12-20 12:38
Hi, @manugarg , thank you for your reply.  
When pinging about 50 targets, the average rtt is in 4~7 ms range, in contrast, when pinging one target, the average rtt is in 1~2 ms range.

I was using the default config in `config.proto`, except that I set `use_datagram_socket` as `false`. BTW, does this setting have effect on latency ?

**Comment by chenlujjj** [comment] 2020-12-20 13:14
The reason why I set use_datagram_socket as false is that, with the default config(use_datagram_socket=true), the ping result shows success=0.  It turns out the `recvPackets` function always return of timeout error: "read udp 0.0.0.0:0: raw-read udp 0.0.0.0:0: i/o timeout". I haven't figure out the cause. My OS is macOS 10.15.6.

**Comment by manugarg** [comment] 2020-12-21 21:46
I've filed #537 to investigate the datagram socket (use_datagram_socket) breakage for MacOS. I could reproduce it on my end (it seems only IPv4 is impacted, IPv6 is fine). Thanks a lot for finding this issue, I was completely unaware of it.

ICMP over datagram socket is slightly more efficient as cloudprober doesn't have to deal with all the ICMP packets in that case. By default, OS delivers all ICMP packets to all applications that are interested in ICMP.

Also, latency increase you're seeing doesn't seem out of ordinary -- lower latency targets do get impacted more because latency increase is constant: 3ms added to 1ms has much bigger impact than say 3ms added to 25ms. I am working on a change that will remove impact of the packet-receiving delays from latency computation; it will take a few days. I'll also try to do some more testing on my end.

**Comment by manugarg** [comment] 2020-12-22 19:27
@chenlujjj Just FYI, I've submitted the fix (#539) for the MacOS datagram socket issue. In case, you want to give it a try.

**Comment by chenlujjj** [comment] 2020-12-23 02:57
@manugarg Thanks, it works well now.

**Comment by manugarg** [comment] 2020-12-23 20:59
Cool. I've also filed #540 to increase accuracy of ping probe latency measurement.

**Comment by manugarg** [comment] 2020-12-24 22:49
Branch https://github.com/google/cloudprober/tree/ping_so_timestamp (#541) has improvements that will make latency measurement much more accurate. Given the holidays, I'll probably not be able to merge these changes in master branch before Jan 1st week or so.

**Comment by manugarg** [comment] 2021-01-06 18:20
@chenlujjj Ping probe latency measurement must be much more accurate after #546. If you're using docker, you can test it with docker tag `master`.  I'll go ahead and close this now. Feel free to re-open if you've any comments.

**Closed by manugarg** 2021-01-06 18:20 UTC
Labels: bug

**Comment by manugarg** [comment] 2021-01-14 02:07
Hi @chenlujjj,

I was wondering if you were able to test the latest changes in your setup. We are seeing much more accurate measurements in our setup now. One example:

https://github.com/google/cloudprober/issues/540#issuecomment-751839854
