### ISSUE TITLE
Support allowed_metrics_regex in Prometheus surfacer

### ISSUE THREAD

**Issue by benner** [google/cloudprober#596] opened 2021-04-29 21:44 UTC
**Describe the feature you'd like and the problem it will solve**

`cloudwatch` and `stackdriver` surfacers has ability to filter which metrics to emit (`allowed_metrics_regex`). It would be greatge to have same functionality for Prometheus surfacer. This can be useful in situation where Prometeus is for monitoring `cloudprober` itself and target metrics is somewhere else.

**Comment by manugarg** [comment] 2021-04-30 18:54
I think this is a duplicate of #590. Please feel free to reopen if it is not.

#597 implements a fix for this.

**Closed by manugarg** 2021-04-30 18:54 UTC
Labels: enhancement
