### ISSUE TITLE
[Enhancement] Dynamic updates from config file

### ISSUE THREAD

**Issue by p-singh** [google/cloudprober#244] opened 2019-06-06 15:56 UTC
Monitor config file regularly to read new probes without having to restart cloudprober again

**Comment by manugarg** [comment] 2019-06-09 21:12
This issue is a duplicate of https://github.com/google/cloudprober/issues/149.

**Comment by manugarg** [comment] 2019-06-10 00:35
Sorry for marking this duplicate without understanding the use case properly.

@p-singh Can you please clarify what kind of setup and use-case you had in mind? In my mind, cloudprober config and binary will be deployed together as one unit. They will be updated at the same time. But that thinking is based on using containers for deployments. Are you using containers as well? or some other form of deployment?

Also, please take a look at the similar issue: #149. I've added some comments there. See if they make sense.

**Comment by p-singh** [comment] 2019-06-10 19:13
@manugarg I am looking for a way for different application owners to use a single deployment of cloudprober. A tentative idea is to provide a web-service interface (separate to the cloudprober) to users to add their specific probes to the configuration file, to get their own monitoring data but without interrupting other running probes.

**Comment by manugarg** [comment] 2019-06-10 21:40
I see. I believe the right way to implement the functionality you want will be to have a gRPC service to add/remove probes (#246). We have talked about it before internally and in the context of other issues (e.g. #206), but haven't started working on creating a specification for that yet. I'll try to take it up soon.

Other than that, I wanted to mention that it should always be okay to restart cloudprober -- it should not cause any visible disruption. Existing probes will be interrupted but if the output data is being ingested properly, it should not cause any blips in your dashboards or cause spurious alerts. Reason for that is -- cloudprober exports cumulative counters and on restart counters will be reset; if you're ingesting these metrics in prometheus, prometheus will automatically figure out that jobs must have been reset and will take that into account while calculating rates for example.

In our setup, teams update the config in a code repository, new config and cloudprober binary are packaged into a new docker image, and that docker image is rolled out to the prober VMs.

I understand your setup is likely more focussed on providing prober as a service and minimizing what teams need to know about the setup, but even in that case, it should be possible to just restart cloudprober with the new config. Your workflow could look something like:

1. Modify the config through a web interface. Users likely just add/edit/remove probes.
2. In the backend, you generate the new config. If you're running multiple cloudprober instances, try re-running one instance with the new config, and if it works, accept the config and update the whole fleet (not sure what kind of tools are you using to manage your deployments).

**Comment by manugarg** [comment] 2019-06-14 10:39
I think https://github.com/google/cloudprober/issues/246 will address the dynamic config update issue. Feel free to reopen if you disagree.

**Closed by manugarg** 2019-06-14 10:39 UTC
